receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:

exporters:
  prometheus:
    endpoint: otel-collector:8889
  otlphttp:
    endpoint: http://loki:3100/otlp
  otlp:
    endpoint: tempo:4007

processors:
  batch:

extensions:
  health_check:
    endpoint: otel-collector:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
      